"""add homography_inlier_ratio to images

Revision ID: 510fd742368b
Revises: e82a08bd8639
Create Date: 2026-05-16 19:26:26.157948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510fd742368b'
down_revision: Union[str, Sequence[str], None] = 'e82a08bd8639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('homography_inlier_ratio', sa.Float(), server_default='0', nullable=False))
    op.add_column('thresholds', sa.Column('homography_inlier_ratio_min', sa.Float(), server_default='0.40', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thresholds', 'homography_inlier_ratio_min')
    op.drop_column('images', 'homography_inlier_ratio')
    # ### end Alembic commands ###
