"""initial schema

Revision ID: e82a08bd8639
Revises: 
Create Date: 2026-05-14 16:10:16.360371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e82a08bd8639'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_image_paths', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('thresholds',
    sa.Column('threshold_id', sa.UUID(), nullable=False),
    sa.Column('ssim_min', sa.Float(), nullable=False),
    sa.Column('match_ratio_min', sa.Float(), nullable=False),
    sa.Column('inliers_min', sa.Integer(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('eval_sample_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('threshold_id')
    )
    op.create_index(op.f('ix_thresholds_is_active'), 'thresholds', ['is_active'], unique=False)
    op.create_table('images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('base_image_path', sa.String(length=1024), nullable=False),
    sa.Column('annotated_path', sa.String(length=1024), nullable=True),
    sa.Column('ssim_score', sa.Float(), nullable=False),
    sa.Column('match_ratio', sa.Float(), nullable=False),
    sa.Column('inliers', sa.Integer(), nullable=False),
    sa.Column('script_decision', sa.Boolean(), nullable=False),
    sa.Column('human_label', sa.Enum('NORMAL', 'OBSTRUCTED', 'MOVED', 'OTHER', name='human_label_enum'), nullable=True),
    sa.Column('synthetic_label', sa.Enum('NORMAL', 'OBSTRUCTED', 'MOVED', 'OTHER', name='human_label_enum'), nullable=True),
    sa.Column('synthetic_transform', sa.String(length=64), nullable=True),
    sa.Column('synthetic_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_images_camera_id'), 'images', ['camera_id'], unique=False)
    op.create_index(op.f('ix_images_timestamp'), 'images', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_timestamp'), table_name='images')
    op.drop_index(op.f('ix_images_camera_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_thresholds_is_active'), table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_table('cameras')
    # ### end Alembic commands ###
